export const worldCountries = [
  // Africa
  { value: "algeria", label: "Algeria" },
  { value: "angola", label: "Angola" },
  { value: "benin", label: "Benin" },
  { value: "botswana", label: "Botswana" },
  { value: "burkina_faso", label: "Burkina Faso" },
  { value: "burundi", label: "Burundi" },
  { value: "cameroon", label: "Cameroon" },
  { value: "cape_verde", label: "Cape Verde" },
  { value: "central_african_republic", label: "Central African Republic" },
  { value: "chad", label: "Chad" },
  { value: "comoros", label: "Comoros" },
  { value: "democratic_republic_of_congo", label: "Democratic Republic of Congo" },
  { value: "djibouti", label: "Djibouti" },
  { value: "egypt", label: "Egypt" },
  { value: "equatorial_guinea", label: "Equatorial Guinea" },
  { value: "eritrea", label: "Eritrea" },
  { value: "eswatini", label: "Eswatini" },
  { value: "ethiopia", label: "Ethiopia" },
  { value: "gabon", label: "Gabon" },
  { value: "gambia", label: "Gambia" },
  { value: "ghana", label: "Ghana" },
  { value: "guinea", label: "Guinea" },
  { value: "guinea_bissau", label: "Guinea-Bissau" },
  { value: "ivory_coast", label: "Ivory Coast" },
  { value: "kenya", label: "Kenya" },
  { value: "lesotho", label: "Lesotho" },
  { value: "liberia", label: "Liberia" },
  { value: "libya", label: "Libya" },
  { value: "madagascar", label: "Madagascar" },
  { value: "malawi", label: "Malawi" },
  { value: "mali", label: "Mali" },
  { value: "mauritania", label: "Mauritania" },
  { value: "mauritius", label: "Mauritius" },
  { value: "morocco", label: "Morocco" },
  { value: "mozambique", label: "Mozambique" },
  { value: "namibia", label: "Namibia" },
  { value: "niger", label: "Niger" },
  { value: "nigeria", label: "Nigeria" },
  { value: "republic_of_the_congo", label: "Republic of the Congo" },
  { value: "rwanda", label: "Rwanda" },
  { value: "sao_tome_and_principe", label: "São Tomé and Príncipe" },
  { value: "senegal", label: "Senegal" },
  { value: "seychelles", label: "Seychelles" },
  { value: "sierra_leone", label: "Sierra Leone" },
  { value: "somalia", label: "Somalia" },
  { value: "south_africa", label: "South Africa" },
  { value: "south_sudan", label: "South Sudan" },
  { value: "sudan", label: "Sudan" },
  { value: "tanzania", label: "Tanzania" },
  { value: "togo", label: "Togo" },
  { value: "tunisia", label: "Tunisia" },
  { value: "uganda", label: "Uganda" },
  { value: "zambia", label: "Zambia" },
  { value: "zimbabwe", label: "Zimbabwe" },

  // Asia
  { value: "afghanistan", label: "Afghanistan" },
  { value: "armenia", label: "Armenia" },
  { value: "azerbaijan", label: "Azerbaijan" },
  { value: "bahrain", label: "Bahrain" },
  { value: "bangladesh", label: "Bangladesh" },
  { value: "bhutan", label: "Bhutan" },
  { value: "brunei", label: "Brunei" },
  { value: "cambodia", label: "Cambodia" },
  { value: "china", label: "China" },
  { value: "cyprus", label: "Cyprus" },
  { value: "georgia", label: "Georgia" },
  { value: "india", label: "India" },
  { value: "indonesia", label: "Indonesia" },
  { value: "iran", label: "Iran" },
  { value: "iraq", label: "Iraq" },
  { value: "israel", label: "Israel" },
  { value: "japan", label: "Japan" },
  { value: "jordan", label: "Jordan" },
  { value: "kazakhstan", label: "Kazakhstan" },
  { value: "kuwait", label: "Kuwait" },
  { value: "kyrgyzstan", label: "Kyrgyzstan" },
  { value: "laos", label: "Laos" },
  { value: "lebanon", label: "Lebanon" },
  { value: "malaysia", label: "Malaysia" },
  { value: "maldives", label: "Maldives" },
  { value: "mongolia", label: "Mongolia" },
  { value: "myanmar", label: "Myanmar" },
  { value: "nepal", label: "Nepal" },
  { value: "north_korea", label: "North Korea" },
  { value: "oman", label: "Oman" },
  { value: "pakistan", label: "Pakistan" },
  { value: "palestine", label: "Palestine" },
  { value: "philippines", label: "Philippines" },
  { value: "qatar", label: "Qatar" },
  { value: "saudi_arabia", label: "Saudi Arabia" },
  { value: "singapore", label: "Singapore" },
  { value: "south_korea", label: "South Korea" },
  { value: "sri_lanka", label: "Sri Lanka" },
  { value: "syria", label: "Syria" },
  { value: "taiwan", label: "Taiwan" },
  { value: "tajikistan", label: "Tajikistan" },
  { value: "thailand", label: "Thailand" },
  { value: "timor_leste", label: "Timor-Leste" },
  { value: "turkey", label: "Turkey" },
  { value: "turkmenistan", label: "Turkmenistan" },
  { value: "united_arab_emirates", label: "United Arab Emirates" },
  { value: "uzbekistan", label: "Uzbekistan" },
  { value: "vietnam", label: "Vietnam" },
  { value: "yemen", label: "Yemen" },

  // Europe
  { value: "albania", label: "Albania" },
  { value: "andorra", label: "Andorra" },
  { value: "austria", label: "Austria" },
  { value: "belarus", label: "Belarus" },
  { value: "belgium", label: "Belgium" },
  { value: "bosnia_and_herzegovina", label: "Bosnia and Herzegovina" },
  { value: "bulgaria", label: "Bulgaria" },
  { value: "croatia", label: "Croatia" },
  { value: "czech_republic", label: "Czech Republic" },
  { value: "denmark", label: "Denmark" },
  { value: "estonia", label: "Estonia" },
  { value: "finland", label: "Finland" },
  { value: "france", label: "France" },
  { value: "germany", label: "Germany" },
  { value: "greece", label: "Greece" },
  { value: "hungary", label: "Hungary" },
  { value: "iceland", label: "Iceland" },
  { value: "ireland", label: "Ireland" },
  { value: "italy", label: "Italy" },
  { value: "kosovo", label: "Kosovo" },
  { value: "latvia", label: "Latvia" },
  { value: "liechtenstein", label: "Liechtenstein" },
  { value: "lithuania", label: "Lithuania" },
  { value: "luxembourg", label: "Luxembourg" },
  { value: "malta", label: "Malta" },
  { value: "moldova", label: "Moldova" },
  { value: "monaco", label: "Monaco" },
  { value: "montenegro", label: "Montenegro" },
  { value: "netherlands", label: "Netherlands" },
  { value: "north_macedonia", label: "North Macedonia" },
  { value: "norway", label: "Norway" },
  { value: "poland", label: "Poland" },
  { value: "portugal", label: "Portugal" },
  { value: "romania", label: "Romania" },
  { value: "russia", label: "Russia" },
  { value: "san_marino", label: "San Marino" },
  { value: "serbia", label: "Serbia" },
  { value: "slovakia", label: "Slovakia" },
  { value: "slovenia", label: "Slovenia" },
  { value: "spain", label: "Spain" },
  { value: "sweden", label: "Sweden" },
  { value: "switzerland", label: "Switzerland" },
  { value: "ukraine", label: "Ukraine" },
  { value: "united_kingdom", label: "United Kingdom" },
  { value: "vatican_city", label: "Vatican City" },

  // North America
  { value: "antigua_and_barbuda", label: "Antigua and Barbuda" },
  { value: "bahamas", label: "Bahamas" },
  { value: "barbados", label: "Barbados" },
  { value: "belize", label: "Belize" },
  { value: "canada", label: "Canada" },
  { value: "costa_rica", label: "Costa Rica" },
  { value: "cuba", label: "Cuba" },
  { value: "dominica", label: "Dominica" },
  { value: "dominican_republic", label: "Dominican Republic" },
  { value: "el_salvador", label: "El Salvador" },
  { value: "grenada", label: "Grenada" },
  { value: "guatemala", label: "Guatemala" },
  { value: "haiti", label: "Haiti" },
  { value: "honduras", label: "Honduras" },
  { value: "jamaica", label: "Jamaica" },
  { value: "mexico", label: "Mexico" },
  { value: "nicaragua", label: "Nicaragua" },
  { value: "panama", label: "Panama" },
  { value: "saint_kitts_and_nevis", label: "Saint Kitts and Nevis" },
  { value: "saint_lucia", label: "Saint Lucia" },
  { value: "saint_vincent_and_the_grenadines", label: "Saint Vincent and the Grenadines" },
  { value: "trinidad_and_tobago", label: "Trinidad and Tobago" },
  { value: "united_states", label: "United States of America" },

  // South America
  { value: "argentina", label: "Argentina" },
  { value: "bolivia", label: "Bolivia" },
  { value: "brazil", label: "Brazil" },
  { value: "chile", label: "Chile" },
  { value: "colombia", label: "Colombia" },
  { value: "ecuador", label: "Ecuador" },
  { value: "guyana", label: "Guyana" },
  { value: "paraguay", label: "Paraguay" },
  { value: "peru", label: "Peru" },
  { value: "suriname", label: "Suriname" },
  { value: "uruguay", label: "Uruguay" },
  { value: "venezuela", label: "Venezuela" },

  // Oceania
  { value: "australia", label: "Australia" },
  { value: "fiji", label: "Fiji" },
  { value: "kiribati", label: "Kiribati" },
  { value: "marshall_islands", label: "Marshall Islands" },
  { value: "micronesia", label: "Micronesia" },
  { value: "nauru", label: "Nauru" },
  { value: "new_zealand", label: "New Zealand" },
  { value: "palau", label: "Palau" },
  { value: "papua_new_guinea", label: "Papua New Guinea" },
  { value: "samoa", label: "Samoa" },
  { value: "solomon_islands", label: "Solomon Islands" },
  { value: "tonga", label: "Tonga" },
  { value: "tuvalu", label: "Tuvalu" },
  { value: "vanuatu", label: "Vanuatu" },
];